# This file contains the fastlane.tools configuration
# for the iOS half of the Skip app.
# You can find the documentation at https://docs.fastlane.tools

default_platform(:ios)

lane :assemble do |options|
  ENV["SKIP_ZERO"] = "true"
  build_app(
    scheme: "Ategal App",
    configuration: "Release",
    sdk: "iphoneos",
    xcconfig: "fastlane/AppStore.xcconfig",
    xcargs: "-skipPackagePluginValidation -skipMacroValidation",
    derived_data_path: "../.build/Darwin/DerivedData",
    output_directory: "../.build/fastlane/Darwin",
    skip_archive: ENV["FASTLANE_SKIP_ARCHIVE"] == "YES",
    skip_codesigning: ENV["FASTLANE_SKIP_CODESIGNING"] == "YES",
    export_method: "app-store",
    export_options: {
      provisioningProfiles: {
        "mr.ategal.app" => "release__22/8/26"
      }
    }
  )
end

lane :release do |options|
  desc "Build and release app"

  upload_app_privacy_details_to_app_store(
    json_path: "fastlane/metadata/app_privacy_details.json"
  )

  assemble

  upload_to_app_store(
    #api_key_path: "fastlane/apikey.json",
    app_rating_config_path: "fastlane/metadata/rating.json",
    release_notes: { "es-ES": "Melloras de rendemento e corrección de erros." }
  )
end
